format = """
[‚ñë‚ñí‚ñì](#a3aed2)\
[ Û∞£á ](bg:#a3aed2 fg:#090c0c)\
[ÓÇ∞](bg:#769ff0 fg:#a3aed2)\
$directory\
[ÓÇ∞](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[ÓÇ∞](fg:#394260 bg:#212736)\
$c\
$rust\
$golang\
$python\
[ÓÇ∞](fg:#212736 bg:#1d2230)\
$time\
[ÓÇ∞ ](fg:#1d2230)\
\n$character"""

right_format = """
$cmd_duration
"""

[cmd_duration]
format = "[ $duration ](italic fg:#a3aed2)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[git_branch]
symbol = "Ôêò"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[c]
symbol = "Óòû"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = "Óû®"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "Óòß"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = "üêç"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ Ôê∫ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
disabled = false
success_symbol = '[Ôê≤](bold fg:#98971a)'
error_symbol = '[Ôê≤](bold fg:#cc241d)'
vimcmd_symbol = '[Ôê¥](bold fg:#98971a)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:#b16286)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:#b16286)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:#d79921)'
